@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package direkt.jooq.keys


import direkt.jooq.tables.AssetLabel
import direkt.jooq.tables.AssetTag
import direkt.jooq.tables.AssetTree
import direkt.jooq.tables.AssetVariant
import direkt.jooq.tables.Outbox
import direkt.jooq.tables.records.AssetLabelRecord
import direkt.jooq.tables.records.AssetTagRecord
import direkt.jooq.tables.records.AssetTreeRecord
import direkt.jooq.tables.records.AssetVariantRecord
import direkt.jooq.tables.records.OutboxRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.QOM.ForeignKeyRule



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val ASSET_LABEL_PKEY: UniqueKey<AssetLabelRecord> = Internal.createUniqueKey(AssetLabel.ASSET_LABEL, DSL.name("asset_label_pkey"), arrayOf(AssetLabel.ASSET_LABEL.ID), true)
val ASSET_TAG_PKEY: UniqueKey<AssetTagRecord> = Internal.createUniqueKey(AssetTag.ASSET_TAG, DSL.name("asset_tag_pkey"), arrayOf(AssetTag.ASSET_TAG.ID), true)
val ASSET_TREE_PKEY: UniqueKey<AssetTreeRecord> = Internal.createUniqueKey(AssetTree.ASSET_TREE, DSL.name("asset_tree_pkey"), arrayOf(AssetTree.ASSET_TREE.ID), true)
val ASSET_VARIANT_PKEY: UniqueKey<AssetVariantRecord> = Internal.createUniqueKey(AssetVariant.ASSET_VARIANT, DSL.name("asset_variant_pkey"), arrayOf(AssetVariant.ASSET_VARIANT.ID), true)
val OUTBOX_PKEY: UniqueKey<OutboxRecord> = Internal.createUniqueKey(Outbox.OUTBOX, DSL.name("outbox_pkey"), arrayOf(Outbox.OUTBOX.ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val ASSET_LABEL__FK_ASSET_LABEL_ASSET_ID_ASSET_TREE_ID: ForeignKey<AssetLabelRecord, AssetTreeRecord> = Internal.createForeignKey(AssetLabel.ASSET_LABEL, DSL.name("fk_asset_label_asset_id_asset_tree_id"), arrayOf(AssetLabel.ASSET_LABEL.ASSET_ID), direkt.jooq.keys.ASSET_TREE_PKEY, arrayOf(AssetTree.ASSET_TREE.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
val ASSET_TAG__FK_ASSET_TAG_ASSET_ID_ASSET_TREE_ID: ForeignKey<AssetTagRecord, AssetTreeRecord> = Internal.createForeignKey(AssetTag.ASSET_TAG, DSL.name("fk_asset_tag_asset_id_asset_tree_id"), arrayOf(AssetTag.ASSET_TAG.ASSET_ID), direkt.jooq.keys.ASSET_TREE_PKEY, arrayOf(AssetTree.ASSET_TREE.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
val ASSET_VARIANT__FK_ASSET_VARIANT_ASSET_ID_ASSET_TREE_ID: ForeignKey<AssetVariantRecord, AssetTreeRecord> = Internal.createForeignKey(AssetVariant.ASSET_VARIANT, DSL.name("fk_asset_variant_asset_id_asset_tree_id"), arrayOf(AssetVariant.ASSET_VARIANT.ASSET_ID), direkt.jooq.keys.ASSET_TREE_PKEY, arrayOf(AssetTree.ASSET_TREE.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
