changelog:
  categories:
    - title: Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: Client
      labels:
        - client
    - title: Dependencies
      labels:
        - dependencies
