@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package direkt.jooq.indexes


import direkt.jooq.tables.AssetLabel
import direkt.jooq.tables.AssetTag
import direkt.jooq.tables.AssetTree
import direkt.jooq.tables.AssetVariant
import direkt.jooq.tables.Outbox

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val ASSET_LABEL_ASSET_ID_IDX: Index = Internal.createIndex(DSL.name("asset_label_asset_id_idx"), AssetLabel.ASSET_LABEL, arrayOf(AssetLabel.ASSET_LABEL.ASSET_ID), false)
val ASSET_LABEL_KEY_VALUE_UQ: Index = Internal.createIndex(DSL.name("asset_label_key_value_uq"), AssetLabel.ASSET_LABEL, arrayOf(AssetLabel.ASSET_LABEL.ASSET_ID, AssetLabel.ASSET_LABEL.LABEL_KEY, AssetLabel.ASSET_LABEL.LABEL_VALUE), true)
val ASSET_TAG_ASSET_ID_IDX: Index = Internal.createIndex(DSL.name("asset_tag_asset_id_idx"), AssetTag.ASSET_TAG, arrayOf(AssetTag.ASSET_TAG.ASSET_ID), false)
val ASSET_TAG_KEY_VALUE_UQ: Index = Internal.createIndex(DSL.name("asset_tag_key_value_uq"), AssetTag.ASSET_TAG, arrayOf(AssetTag.ASSET_TAG.ASSET_ID, AssetTag.ASSET_TAG.TAG_VALUE), true)
val ASSET_TREE_NOT_READY: Index = Internal.createIndex(DSL.name("asset_tree_not_ready"), AssetTree.ASSET_TREE, arrayOf(AssetTree.ASSET_TREE.ID), false)
val ASSET_TREE_PATH_ENTRY_ID_UQ: Index = Internal.createIndex(DSL.name("asset_tree_path_entry_id_uq"), AssetTree.ASSET_TREE, arrayOf(AssetTree.ASSET_TREE.PATH, AssetTree.ASSET_TREE.ENTRY_ID), true)
val ASSET_TREE_PATH_GIST_IDX: Index = Internal.createIndex(DSL.name("asset_tree_path_gist_idx"), AssetTree.ASSET_TREE, arrayOf(AssetTree.ASSET_TREE.PATH), false)
val ASSET_TREE_PATH_IS_READY_IDX: Index = Internal.createIndex(DSL.name("asset_tree_path_is_ready_idx"), AssetTree.ASSET_TREE, arrayOf(AssetTree.ASSET_TREE.PATH, AssetTree.ASSET_TREE.IS_READY), false)
val ASSET_VARIANT_ASSET_ID_IDX: Index = Internal.createIndex(DSL.name("asset_variant_asset_id_idx"), AssetVariant.ASSET_VARIANT, arrayOf(AssetVariant.ASSET_VARIANT.ASSET_ID), false)
val ASSET_VARIANT_ASSET_ID_ORIGINAL_VARIANT_UQ: Index = Internal.createIndex(DSL.name("asset_variant_asset_id_original_variant_uq"), AssetVariant.ASSET_VARIANT, arrayOf(AssetVariant.ASSET_VARIANT.ASSET_ID), true)
val ASSET_VARIANT_NOT_UPLOADED: Index = Internal.createIndex(DSL.name("asset_variant_not_uploaded"), AssetVariant.ASSET_VARIANT, arrayOf(AssetVariant.ASSET_VARIANT.ID), false)
val ASSET_VARIANT_TRANSFORMATION_UQ: Index = Internal.createIndex(DSL.name("asset_variant_transformation_uq"), AssetVariant.ASSET_VARIANT, arrayOf(AssetVariant.ASSET_VARIANT.ASSET_ID, AssetVariant.ASSET_VARIANT.TRANSFORMATION), true)
val OUTBOX_EVENT_TYPE_IDX: Index = Internal.createIndex(DSL.name("outbox_event_type_idx"), Outbox.OUTBOX, arrayOf(Outbox.OUTBOX.EVENT_TYPE), false)
