ALTER TABLE IF EXISTS asset_variant
    ADD COLUMN IF NOT EXISTS access_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS access_score_as_of TIMESTAMP WITHOUT TIME ZONE NOT NULL
        DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC');
