/*
 * This file is generated by jOOQ.
 */
package konifer.jooq.tables.records


import java.time.LocalDateTime
import java.util.UUID

import konifer.jooq.tables.Outbox

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class OutboxRecord() : UpdatableRecordImpl<OutboxRecord>(Outbox.OUTBOX) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var eventType: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var payload: JSONB?
        set(value): Unit = set(2, value)
        get(): JSONB? = get(2) as JSONB?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised OutboxRecord
     */
    constructor(id: UUID? = null, eventType: String? = null, payload: JSONB? = null, createdAt: LocalDateTime? = null): this() {
        this.id = id
        this.eventType = eventType
        this.payload = payload
        this.createdAt = createdAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised OutboxRecord
     */
    constructor(value: konifer.jooq.tables.pojos.Outbox?): this() {
        if (value != null) {
            this.id = value.id
            this.eventType = value.eventType
            this.payload = value.payload
            this.createdAt = value.createdAt
            resetTouchedOnNotNull()
        }
    }
}
