/*
 * This file is generated by jOOQ.
 */
package konifer.jooq.tables.records


import java.time.LocalDateTime
import java.util.UUID

import konifer.jooq.tables.PromptEmbedding

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class PromptEmbeddingRecord() : UpdatableRecordImpl<PromptEmbeddingRecord>(PromptEmbedding.PROMPT_EMBEDDING) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var model: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var promptText: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var embedding: Array<Float?>?
        set(value): Unit = set(3, value)
        get(): Array<Float?>? = get(3) as Array<Float?>?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(4, value)
        get(): LocalDateTime? = get(4) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised PromptEmbeddingRecord
     */
    constructor(id: UUID? = null, model: String? = null, promptText: String? = null, embedding: Array<Float?>? = null, createdAt: LocalDateTime? = null): this() {
        this.id = id
        this.model = model
        this.promptText = promptText
        this.embedding = embedding
        this.createdAt = createdAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised PromptEmbeddingRecord
     */
    constructor(value: konifer.jooq.tables.pojos.PromptEmbedding?): this() {
        if (value != null) {
            this.id = value.id
            this.model = value.model
            this.promptText = value.promptText
            this.embedding = value.embedding
            this.createdAt = value.createdAt
            resetTouchedOnNotNull()
        }
    }
}
