@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package direkt.jooq.tables.references


import direkt.jooq.tables.AssetLabel
import direkt.jooq.tables.AssetTag
import direkt.jooq.tables.AssetTree
import direkt.jooq.tables.AssetVariant



/**
 * The table <code>public.asset_label</code>.
 */
val ASSET_LABEL: AssetLabel = AssetLabel.ASSET_LABEL

/**
 * The table <code>public.asset_tag</code>.
 */
val ASSET_TAG: AssetTag = AssetTag.ASSET_TAG

/**
 * The table <code>public.asset_tree</code>.
 */
val ASSET_TREE: AssetTree = AssetTree.ASSET_TREE

/**
 * The table <code>public.asset_variant</code>.
 */
val ASSET_VARIANT: AssetVariant = AssetVariant.ASSET_VARIANT
