/*
 * This file is generated by jOOQ.
 */
package konifer.jooq


import konifer.jooq.tables.AssetLabel
import konifer.jooq.tables.AssetTag
import konifer.jooq.tables.AssetTree
import konifer.jooq.tables.AssetVariant
import konifer.jooq.tables.Outbox

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl


/**
 * standard public schema
 */
@Suppress("warnings")
open class Public : SchemaImpl(DSL.name("public"), DefaultCatalog.DEFAULT_CATALOG, DSL.comment("standard public schema")) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.asset_label</code>.
     */
    val ASSET_LABEL: AssetLabel get() = AssetLabel.ASSET_LABEL

    /**
     * The table <code>public.asset_tag</code>.
     */
    val ASSET_TAG: AssetTag get() = AssetTag.ASSET_TAG

    /**
     * The table <code>public.asset_tree</code>.
     */
    val ASSET_TREE: AssetTree get() = AssetTree.ASSET_TREE

    /**
     * The table <code>public.asset_variant</code>.
     */
    val ASSET_VARIANT: AssetVariant get() = AssetVariant.ASSET_VARIANT

    /**
     * The table <code>public.outbox</code>.
     */
    val OUTBOX: Outbox get() = Outbox.OUTBOX

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        AssetLabel.ASSET_LABEL,
        AssetTag.ASSET_TAG,
        AssetTree.ASSET_TREE,
        AssetVariant.ASSET_VARIANT,
        Outbox.OUTBOX
    )
}
