/*
 * This file is generated by jOOQ.
 */
package direkt.jooq.tables.records


import direkt.jooq.tables.AssetTree

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.postgres.extensions.types.Ltree


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class AssetTreeRecord() : UpdatableRecordImpl<AssetTreeRecord>(AssetTree.ASSET_TREE) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var entryId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var path: Ltree?
        set(value): Unit = set(2, value)
        get(): Ltree? = get(2) as Ltree?

    open var alt: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var source: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var sourceUrl: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsReady")
    open var isReady: Boolean?
        set(value): Unit = set(6, value)
        get(): Boolean? = get(6) as Boolean?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    open var modifiedAt: LocalDateTime?
        set(value): Unit = set(8, value)
        get(): LocalDateTime? = get(8) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised AssetTreeRecord
     */
    constructor(id: UUID? = null, entryId: Long? = null, path: Ltree? = null, alt: String? = null, source: String? = null, sourceUrl: String? = null, isReady: Boolean? = null, createdAt: LocalDateTime? = null, modifiedAt: LocalDateTime? = null): this() {
        this.id = id
        this.entryId = entryId
        this.path = path
        this.alt = alt
        this.source = source
        this.sourceUrl = sourceUrl
        this.isReady = isReady
        this.createdAt = createdAt
        this.modifiedAt = modifiedAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised AssetTreeRecord
     */
    constructor(value: direkt.jooq.tables.pojos.AssetTree?): this() {
        if (value != null) {
            this.id = value.id
            this.entryId = value.entryId
            this.path = value.path
            this.alt = value.alt
            this.source = value.source
            this.sourceUrl = value.sourceUrl
            this.isReady = value.isReady
            this.createdAt = value.createdAt
            this.modifiedAt = value.modifiedAt
            resetTouchedOnNotNull()
        }
    }
}
