/*
 * This file is generated by jOOQ.
 */
package direkt.jooq.tables.records


import direkt.jooq.tables.AssetTag

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class AssetTagRecord() : UpdatableRecordImpl<AssetTagRecord>(AssetTag.ASSET_TAG) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var assetId: UUID?
        set(value): Unit = set(1, value)
        get(): UUID? = get(1) as UUID?

    open var tagValue: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised AssetTagRecord
     */
    constructor(id: UUID? = null, assetId: UUID? = null, tagValue: String? = null, createdAt: LocalDateTime? = null): this() {
        this.id = id
        this.assetId = assetId
        this.tagValue = tagValue
        this.createdAt = createdAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised AssetTagRecord
     */
    constructor(value: direkt.jooq.tables.pojos.AssetTag?): this() {
        if (value != null) {
            this.id = value.id
            this.assetId = value.assetId
            this.tagValue = value.tagValue
            this.createdAt = value.createdAt
            resetTouchedOnNotNull()
        }
    }
}
