/*
 * This file is generated by jOOQ.
 */
package direkt.jooq.tables.records


import direkt.jooq.tables.AssetVariant

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class AssetVariantRecord() : UpdatableRecordImpl<AssetVariantRecord>(AssetVariant.ASSET_VARIANT) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var assetId: UUID?
        set(value): Unit = set(1, value)
        get(): UUID? = get(1) as UUID?

    open var objectStoreBucket: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var objectStoreKey: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var transformation: JSONB?
        set(value): Unit = set(4, value)
        get(): JSONB? = get(4) as JSONB?

    open var attributes: JSONB?
        set(value): Unit = set(5, value)
        get(): JSONB? = get(5) as JSONB?

    open var lqip: JSONB?
        set(value): Unit = set(6, value)
        get(): JSONB? = get(6) as JSONB?

    open var originalVariant: Boolean?
        set(value): Unit = set(7, value)
        get(): Boolean? = get(7) as Boolean?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(8, value)
        get(): LocalDateTime? = get(8) as LocalDateTime?

    open var uploadedAt: LocalDateTime?
        set(value): Unit = set(9, value)
        get(): LocalDateTime? = get(9) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised AssetVariantRecord
     */
    constructor(id: UUID? = null, assetId: UUID? = null, objectStoreBucket: String? = null, objectStoreKey: String? = null, transformation: JSONB? = null, attributes: JSONB? = null, lqip: JSONB? = null, originalVariant: Boolean? = null, createdAt: LocalDateTime? = null, uploadedAt: LocalDateTime? = null): this() {
        this.id = id
        this.assetId = assetId
        this.objectStoreBucket = objectStoreBucket
        this.objectStoreKey = objectStoreKey
        this.transformation = transformation
        this.attributes = attributes
        this.lqip = lqip
        this.originalVariant = originalVariant
        this.createdAt = createdAt
        this.uploadedAt = uploadedAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised AssetVariantRecord
     */
    constructor(value: direkt.jooq.tables.pojos.AssetVariant?): this() {
        if (value != null) {
            this.id = value.id
            this.assetId = value.assetId
            this.objectStoreBucket = value.objectStoreBucket
            this.objectStoreKey = value.objectStoreKey
            this.transformation = value.transformation
            this.attributes = value.attributes
            this.lqip = value.lqip
            this.originalVariant = value.originalVariant
            this.createdAt = value.createdAt
            this.uploadedAt = value.uploadedAt
            resetTouchedOnNotNull()
        }
    }
}
