/*
 * This file is generated by jOOQ.
 */
package direkt.jooq.tables.pojos


import org.jooq.JSONB
import java.io.Serializable
import java.time.LocalDateTime
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class AssetVariant(
    var id: UUID,
    var assetId: UUID,
    var objectStoreBucket: String,
    var objectStoreKey: String,
    var transformation: JSONB,
    var transformationKey: Long,
    var attributes: JSONB,
    var lqip: JSONB,
    var originalVariant: Boolean,
    var createdAt: LocalDateTime
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: AssetVariant = other as AssetVariant
        if (this.id != o.id)
            return false
        if (this.assetId != o.assetId)
            return false
        if (this.objectStoreBucket != o.objectStoreBucket)
            return false
        if (this.objectStoreKey != o.objectStoreKey)
            return false
        if (this.transformation != o.transformation)
            return false
        if (this.transformationKey != o.transformationKey)
            return false
        if (this.attributes != o.attributes)
            return false
        if (this.lqip != o.lqip)
            return false
        if (this.originalVariant != o.originalVariant)
            return false
        if (this.createdAt != o.createdAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.assetId.hashCode()
        result = prime * result + this.objectStoreBucket.hashCode()
        result = prime * result + this.objectStoreKey.hashCode()
        result = prime * result + this.transformation.hashCode()
        result = prime * result + this.transformationKey.hashCode()
        result = prime * result + this.attributes.hashCode()
        result = prime * result + this.lqip.hashCode()
        result = prime * result + this.originalVariant.hashCode()
        result = prime * result + this.createdAt.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("AssetVariant (")

        sb.append(id)
        sb.append(", ").append(assetId)
        sb.append(", ").append(objectStoreBucket)
        sb.append(", ").append(objectStoreKey)
        sb.append(", ").append(transformation)
        sb.append(", ").append(transformationKey)
        sb.append(", ").append(attributes)
        sb.append(", ").append(lqip)
        sb.append(", ").append(originalVariant)
        sb.append(", ").append(createdAt)

        sb.append(")")
        return sb.toString()
    }
}
