/*
 * This file is generated by jOOQ.
 */
package direkt.jooq.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime
import java.util.UUID

import org.jooq.postgres.extensions.types.Ltree


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class AssetTree(
    var id: UUID,
    var entryId: Long,
    var path: Ltree,
    var alt: String? = null,
    var source: String,
    var sourceUrl: String? = null,
    var createdAt: LocalDateTime
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: AssetTree = other as AssetTree
        if (this.id != o.id)
            return false
        if (this.entryId != o.entryId)
            return false
        if (this.path != o.path)
            return false
        if (this.alt == null) {
            if (o.alt != null)
                return false
        }
        else if (this.alt != o.alt)
            return false
        if (this.source != o.source)
            return false
        if (this.sourceUrl == null) {
            if (o.sourceUrl != null)
                return false
        }
        else if (this.sourceUrl != o.sourceUrl)
            return false
        if (this.createdAt != o.createdAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.entryId.hashCode()
        result = prime * result + this.path.hashCode()
        result = prime * result + (if (this.alt == null) 0 else this.alt.hashCode())
        result = prime * result + this.source.hashCode()
        result = prime * result + (if (this.sourceUrl == null) 0 else this.sourceUrl.hashCode())
        result = prime * result + this.createdAt.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("AssetTree (")

        sb.append(id)
        sb.append(", ").append(entryId)
        sb.append(", ").append(path)
        sb.append(", ").append(alt)
        sb.append(", ").append(source)
        sb.append(", ").append(sourceUrl)
        sb.append(", ").append(createdAt)

        sb.append(")")
        return sb.toString()
    }
}
