/*
 * This file is generated by jOOQ.
 */
package direkt.jooq.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime
import java.util.UUID

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class Outbox(
    var id: UUID,
    var eventType: String,
    var payload: JSONB? = null,
    var createdAt: LocalDateTime
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Outbox = other as Outbox
        if (this.id != o.id)
            return false
        if (this.eventType != o.eventType)
            return false
        if (this.payload == null) {
            if (o.payload != null)
                return false
        }
        else if (this.payload != o.payload)
            return false
        if (this.createdAt != o.createdAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.eventType.hashCode()
        result = prime * result + (if (this.payload == null) 0 else this.payload.hashCode())
        result = prime * result + this.createdAt.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Outbox (")

        sb.append(id)
        sb.append(", ").append(eventType)
        sb.append(", ").append(payload)
        sb.append(", ").append(createdAt)

        sb.append(")")
        return sb.toString()
    }
}
