@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package konifer.jooq.tables.references


import konifer.jooq.tables.AssetLabel
import konifer.jooq.tables.AssetTag
import konifer.jooq.tables.AssetTree
import konifer.jooq.tables.AssetVariant
import konifer.jooq.tables.Outbox



/**
 * The table <code>public.asset_label</code>.
 */
val ASSET_LABEL: AssetLabel = AssetLabel.ASSET_LABEL

/**
 * The table <code>public.asset_tag</code>.
 */
val ASSET_TAG: AssetTag = AssetTag.ASSET_TAG

/**
 * The table <code>public.asset_tree</code>.
 */
val ASSET_TREE: AssetTree = AssetTree.ASSET_TREE

/**
 * The table <code>public.asset_variant</code>.
 */
val ASSET_VARIANT: AssetVariant = AssetVariant.ASSET_VARIANT

/**
 * The table <code>public.outbox</code>.
 */
val OUTBOX: Outbox = Outbox.OUTBOX
