/*
 * This file is generated by jOOQ.
 */
package konifer.jooq.tables


import java.time.LocalDateTime
import java.util.UUID

import konifer.jooq.Public
import konifer.jooq.indexes.ASSET_TAG_ASSET_ID_IDX
import konifer.jooq.indexes.ASSET_TAG_KEY_VALUE_UQ
import konifer.jooq.keys.ASSET_TAG_PKEY
import konifer.jooq.keys.ASSET_TAG__FK_ASSET_TAG_ASSET_ID_ASSET_TREE_ID
import konifer.jooq.tables.AssetTree.AssetTreePath
import konifer.jooq.tables.records.AssetTagRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class AssetTag(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, AssetTagRecord>?,
    parentPath: InverseForeignKey<out Record, AssetTagRecord>?,
    aliased: Table<AssetTagRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<AssetTagRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.asset_tag</code>
         */
        val ASSET_TAG: AssetTag = AssetTag()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AssetTagRecord> = AssetTagRecord::class.java

    /**
     * The column <code>public.asset_tag.id</code>.
     */
    val ID: TableField<AssetTagRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.asset_tag.asset_id</code>.
     */
    val ASSET_ID: TableField<AssetTagRecord, UUID?> = createField(DSL.name("asset_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.asset_tag.tag_value</code>.
     */
    val TAG_VALUE: TableField<AssetTagRecord, String?> = createField(DSL.name("tag_value"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.asset_tag.created_at</code>.
     */
    val CREATED_AT: TableField<AssetTagRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<AssetTagRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<AssetTagRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<AssetTagRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.asset_tag</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.asset_tag</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.asset_tag</code> table reference
     */
    constructor(): this(DSL.name("asset_tag"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AssetTagRecord>?, parentPath: InverseForeignKey<out Record, AssetTagRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, ASSET_TAG, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class AssetTagPath : AssetTag, Path<AssetTagRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AssetTagRecord>?, parentPath: InverseForeignKey<out Record, AssetTagRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<AssetTagRecord>): super(alias, aliased)
        override fun `as`(alias: String): AssetTagPath = AssetTagPath(DSL.name(alias), this)
        override fun `as`(alias: Name): AssetTagPath = AssetTagPath(alias, this)
        override fun `as`(alias: Table<*>): AssetTagPath = AssetTagPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(ASSET_TAG_ASSET_ID_IDX, ASSET_TAG_KEY_VALUE_UQ)
    override fun getPrimaryKey(): UniqueKey<AssetTagRecord> = ASSET_TAG_PKEY
    override fun getReferences(): List<ForeignKey<AssetTagRecord, *>> = listOf(ASSET_TAG__FK_ASSET_TAG_ASSET_ID_ASSET_TREE_ID)

    /**
     * Get the implicit join path to the <code>public.asset_tree</code> table.
     */
    fun assetTree(): AssetTreePath = assetTree
    val assetTree: AssetTreePath by lazy { AssetTreePath(this, ASSET_TAG__FK_ASSET_TAG_ASSET_ID_ASSET_TREE_ID, null) }
    override fun `as`(alias: String): AssetTag = AssetTag(DSL.name(alias), this)
    override fun `as`(alias: Name): AssetTag = AssetTag(alias, this)
    override fun `as`(alias: Table<*>): AssetTag = AssetTag(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AssetTag = AssetTag(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AssetTag = AssetTag(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): AssetTag = AssetTag(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): AssetTag = AssetTag(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): AssetTag = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): AssetTag = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): AssetTag = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): AssetTag = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): AssetTag = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): AssetTag = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): AssetTag = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): AssetTag = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): AssetTag = where(DSL.notExists(select))
}
