/*
 * This file is generated by jOOQ.
 */
package konifer.jooq.tables


import java.time.LocalDateTime
import java.util.UUID

import konifer.jooq.Public
import konifer.jooq.indexes.OUTBOX_EVENT_TYPE_IDX
import konifer.jooq.keys.OUTBOX_PKEY
import konifer.jooq.tables.records.OutboxRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Outbox(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, OutboxRecord>?,
    parentPath: InverseForeignKey<out Record, OutboxRecord>?,
    aliased: Table<OutboxRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<OutboxRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.outbox</code>
         */
        val OUTBOX: Outbox = Outbox()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<OutboxRecord> = OutboxRecord::class.java

    /**
     * The column <code>public.outbox.id</code>.
     */
    val ID: TableField<OutboxRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.outbox.event_type</code>.
     */
    val EVENT_TYPE: TableField<OutboxRecord, String?> = createField(DSL.name("event_type"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.outbox.payload</code>.
     */
    val PAYLOAD: TableField<OutboxRecord, JSONB?> = createField(DSL.name("payload"), SQLDataType.JSONB, this, "")

    /**
     * The column <code>public.outbox.created_at</code>.
     */
    val CREATED_AT: TableField<OutboxRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<OutboxRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<OutboxRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<OutboxRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.outbox</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.outbox</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.outbox</code> table reference
     */
    constructor(): this(DSL.name("outbox"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(OUTBOX_EVENT_TYPE_IDX)
    override fun getPrimaryKey(): UniqueKey<OutboxRecord> = OUTBOX_PKEY
    override fun `as`(alias: String): Outbox = Outbox(DSL.name(alias), this)
    override fun `as`(alias: Name): Outbox = Outbox(alias, this)
    override fun `as`(alias: Table<*>): Outbox = Outbox(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Outbox = Outbox(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Outbox = Outbox(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Outbox = Outbox(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Outbox = Outbox(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Outbox = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Outbox = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Outbox = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Outbox = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Outbox = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Outbox = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Outbox = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Outbox = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Outbox = where(DSL.notExists(select))
}
