/*
 * This file is generated by jOOQ.
 */
package konifer.jooq.tables


import java.time.LocalDateTime
import java.util.UUID

import konifer.jooq.Public
import konifer.jooq.indexes.PROMPT_EMBEDDING_CACHE_UQ
import konifer.jooq.keys.PROMPT_EMBEDDING_PKEY
import konifer.jooq.tables.records.PromptEmbeddingRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class PromptEmbedding(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PromptEmbeddingRecord>?,
    parentPath: InverseForeignKey<out Record, PromptEmbeddingRecord>?,
    aliased: Table<PromptEmbeddingRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PromptEmbeddingRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.prompt_embedding</code>
         */
        val PROMPT_EMBEDDING: PromptEmbedding = PromptEmbedding()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PromptEmbeddingRecord> = PromptEmbeddingRecord::class.java

    /**
     * The column <code>public.prompt_embedding.id</code>.
     */
    val ID: TableField<PromptEmbeddingRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.prompt_embedding.model</code>.
     */
    val MODEL: TableField<PromptEmbeddingRecord, String?> = createField(DSL.name("model"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.prompt_embedding.prompt_text</code>.
     */
    val PROMPT_TEXT: TableField<PromptEmbeddingRecord, String?> = createField(DSL.name("prompt_text"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.prompt_embedding.embedding</code>.
     */
    val EMBEDDING: TableField<PromptEmbeddingRecord, Array<Float?>?> = createField(DSL.name("embedding"), SQLDataType.REAL.array().nullable(false), this, "")

    /**
     * The column <code>public.prompt_embedding.created_at</code>.
     */
    val CREATED_AT: TableField<PromptEmbeddingRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<PromptEmbeddingRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PromptEmbeddingRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PromptEmbeddingRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.prompt_embedding</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.prompt_embedding</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.prompt_embedding</code> table reference
     */
    constructor(): this(DSL.name("prompt_embedding"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(PROMPT_EMBEDDING_CACHE_UQ)
    override fun getPrimaryKey(): UniqueKey<PromptEmbeddingRecord> = PROMPT_EMBEDDING_PKEY
    override fun `as`(alias: String): PromptEmbedding = PromptEmbedding(DSL.name(alias), this)
    override fun `as`(alias: Name): PromptEmbedding = PromptEmbedding(alias, this)
    override fun `as`(alias: Table<*>): PromptEmbedding = PromptEmbedding(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PromptEmbedding = PromptEmbedding(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PromptEmbedding = PromptEmbedding(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PromptEmbedding = PromptEmbedding(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): PromptEmbedding = PromptEmbedding(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): PromptEmbedding = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): PromptEmbedding = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): PromptEmbedding = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): PromptEmbedding = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): PromptEmbedding = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): PromptEmbedding = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): PromptEmbedding = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): PromptEmbedding = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): PromptEmbedding = where(DSL.notExists(select))
}
