/*
 * This file is generated by jOOQ.
 */
package konifer.jooq.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class AssetTag(
    var id: UUID,
    var assetId: UUID,
    var tagValue: String,
    var createdAt: LocalDateTime
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: AssetTag = other as AssetTag
        if (this.id != o.id)
            return false
        if (this.assetId != o.assetId)
            return false
        if (this.tagValue != o.tagValue)
            return false
        if (this.createdAt != o.createdAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.assetId.hashCode()
        result = prime * result + this.tagValue.hashCode()
        result = prime * result + this.createdAt.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("AssetTag (")

        sb.append(id)
        sb.append(", ").append(assetId)
        sb.append(", ").append(tagValue)
        sb.append(", ").append(createdAt)

        sb.append(")")
        return sb.toString()
    }
}
