/*
 * This file is generated by jOOQ.
 */
package konifer.jooq.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime
import java.util.Arrays
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class PromptEmbedding(
    var id: UUID,
    var model: String,
    var promptText: String,
    var embedding: Array<Float?>,
    var createdAt: LocalDateTime
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: PromptEmbedding = other as PromptEmbedding
        if (this.id != o.id)
            return false
        if (this.model != o.model)
            return false
        if (this.promptText != o.promptText)
            return false
        if (!Arrays.deepEquals(this.embedding, o.embedding))
            return false
        if (this.createdAt != o.createdAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.model.hashCode()
        result = prime * result + this.promptText.hashCode()
        result = prime * result + Arrays.deepHashCode(this.embedding)
        result = prime * result + this.createdAt.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("PromptEmbedding (")

        sb.append(id)
        sb.append(", ").append(model)
        sb.append(", ").append(promptText)
        sb.append(", ").append(Arrays.deepToString(embedding))
        sb.append(", ").append(createdAt)

        sb.append(")")
        return sb.toString()
    }
}
